name: markdown
version: 0.9.0-dev
author: Dart Team <misc@dartlang.org>
description: A library for converting markdown to HTML.
homepage: https://github.com/dart-lang/markdown
environment:
  sdk: '>=1.12.0 <2.0.0'
dev_dependencies:
  args: '^0.13.3+1'
  path: '^1.3.1'
  test: '^0.12.4+1'
  yaml: '^2.1.8'
